In [1]:
import pandas as pd
import numpy as np
from pandas import datetime
from matplotlib import pyplot as plt

<ipython-input-1-0c95b2fc7292>:3: FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead.
  from pandas import datetime

In [2]:

"""
Load AirQualityUCI Data
"""

def parser(x):
    return datetime.strptime(x, '%Y-%m-%d %H:%M:%S')

input_file = './data/AirQualityUCI_refined.csv'

df = pd.read_csv(input_file,
                 index_col=[0],
                 parse_dates=[0],
                 date_parser=parser)

df

,CO(GT),PT08.S1(CO),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),RH,AH,C6H6(GT)
Datetime,,,,,,,,,,,
2004-03-10 18:00:00,2.6,1360.0,1046.0,166.0,1056.0,113.0,1692.0,1268.0,48.9,0.7578,11.9
2004-03-10 19:00:00,2.0,1292.0,955.0,103.0,1174.0,92.0,1559.0,972.0,47.7,0.7255,9.4
2004-03-10 20:00:00,2.2,1402.0,939.0,131.0,1140.0,114.0,1555.0,1074.0,54.0,0.7502,9.0
2004-03-10 21:00:00,2.2,1376.0,948.0,172.0,1092.0,122.0,1584.0,1203.0,60.0,0.7867,9.2
2004-03-10 22:00:00,1.6,1272.0,836.0,131.0,1205.0,116.0,1490.0,1110.0,59.6,0.7888,6.5
...,...,...,...,...,...,...,...,...,...,...,...
2005-04-04 10:00:00,3.1,1314.0,1101.0,472.0,539.0,190.0,1374.0,1729.0,29.3,0.7568,13.5
2005-04-04 11:00:00,2.4,1163.0,1027.0,353.0,604.0,179.0,1264.0,1269.0,23.7,0.7119,11.4
2005-04-04 12:00:00,2.4,1142.0,1063.0,293.0,603.0,175.0,1241.0,1092.0,18.3,0.6406,12.4
2005-04-04 13:00:00,2.1,1003.0,961.0,235.0,702.0,156.0,1041.0,770.0,13.5,0.5139,9.5
2005-04-04 14:00:00,2.2,1071.0,1047.0,265.0,654.0,168.0,1129.0,816.0,13.1,0.5028,11.9

In [3]:

# Visualization setup
%matplotlib
%config InlineBackend.figure_format = 'svg'

from matplotlib import pyplot as plt
plt.rcParams['figure.figsize'] = [10, 5]
plt.ion() # enable the interactive mode

import seaborn as sns
sns.set()  # set plot styles


# Interpolate for entire data
df.interpolate(inplace=True)
df.info()

Using matplotlib backend: TkAgg
<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 9357 entries, 2004-03-10 18:00:00 to 2005-04-04 14:00:00
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   CO(GT)         9357 non-null   float64
 1   PT08.S1(CO)    9357 non-null   float64
 2   PT08.S2(NMHC)  9357 non-null   float64
 3   NOx(GT)        9357 non-null   float64
 4   PT08.S3(NOx)   9357 non-null   float64
 5   NO2(GT)        9357 non-null   float64
 6   PT08.S4(NO2)   9357 non-null   float64
 7   PT08.S5(O3)    9357 non-null   float64
 8   RH             9357 non-null   float64
 9   AH             9357 non-null   float64
 10  C6H6(GT)       9357 non-null   float64
dtypes: float64(11)
memory usage: 877.2 KB

In [ ]:

"""
Correlation Matrix
"""
sns.pairplot(df, kind='reg', diag_kind='kde',
             plot_kws={'scatter_kws': {'alpha': 0.1}})


# Prepare a feature set
X = df.iloc[:, 1:]    # input features
X

y = df.iloc[:, 0]    # target variable
y

In [ ]:

"""
Feature Importance
"""

# Create and train model for regression

from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor()
model.fit(x, y)


# Print feature importances
print(model.feature_importances_)


# Plot the feature importances
feat_importances = pd.Series(model.feature_importances_, index=X.columns)
feat_importances.nlargest(10).plot(kind='barh')
plt.show()